# Generated by Django 2.1.7 on 2019-03-30 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='thumbnails/groups')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_groups', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat group',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('media_type', models.CharField(choices=[('N', 'Not defined'), ('A', 'Audio'), ('I', 'Image'), ('V', 'Video')], default='N', max_length=1)),
                ('file', models.FileField(upload_to='chatMe_media')),
            ],
            options={
                'verbose_name': 'Media element',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'not_defined'), ('S', 'Single user'), ('G', 'Group'), ('A', 'All users')], default='N', max_length=1)),
                ('content', models.CharField(max_length=512)),
                ('date', models.DateTimeField(auto_now=True)),
                ('has_been_read', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatMe.Group')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatMe.Media')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
