# Generated by Django 2.1.7 on 2019-03-30 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('group_date', models.DateTimeField(auto_now=True)),
                ('group_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatMe.Media')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupUser_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatMe.Group')),
                ('groupUser_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=150)),
                ('message_date', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('N', 'Not defined'), ('S', 'Single_User'), ('G', 'Group_Users'), ('A', 'All_Server')], default='N', max_length=1)),
                ('message_status', models.BooleanField(default=False)),
                ('message_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatMe.Group')),
                ('message_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatMe.Media')),
                ('message_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to=settings.AUTH_USER_MODEL)),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Mesaj Gönderen')),
            ],
        ),
    ]
